name: Build and deploy JAR app to Azure Web App - ms-products-kevsa
on:
  push:
    branches:
      - test
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      SPRING_PROFILES_ACTIVE: dev
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_DB: ${{ vars.MONGO_DB }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Build with Maven
        run: mvn clean install
        env:
          SPRING_PROFILES_ACTIVE: dev
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: ${{ vars.MONGO_DB }}
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_112B48BCC52247068AD8EFA68D3F29D7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0B6A5F150C6048FE9F5C9335A718F7C2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0DD67D4DF0F148BA8A5A0431FAD9EEBA }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ms-products-kevsa'
          slot-name: 'Production'
          package: '*.jar'
